version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "10.104.1.10:7777:8096"
    container_name: jellyfin
    volumes:
      - /home/server/nfs/config:/config
      - /home/server/nfs/cache:/cache
      - /home/server/nfs/media:/media
      - /home/server/nfs/media2:/media2:ro
    restart: 'unless-stopped'

